name: CI
on:
  push:
  pull_request:

env:
    DOTNET_VERSION: '9.0.x'

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        name: Build & Test

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Restore dependencies
              run: dotnet restore
              working-directory: ./src/TailspinToys.Web

            - name: Build
              run: dotnet build --configuration Release --no-restore
              working-directory: ./src/TailspinToys.Web

            - name: Run tests
              run: dotnet test --configuration Release --no-build --verbosity normal
              working-directory: ./tests/TailspinToys.Web.Tests
